export const MAIN_ROUTE = '/main'
export const PRODUCT_ROUTE = '/product/:id'
export const LOGIN_ROUTE = '/login'
export const SEARCH_ROUTE = '/search'
export const ADD_ROUTE = '/add'
export const CART_ROUTE = '/cart'
export const CHAT_ROUTE = '/chat'